// <auto-generated />
namespace Assignment2_3.Migrations.ClientsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Validation0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Validation0));
        
        string IMigrationMetadata.Id
        {
            get { return "201503050524385_Validation0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
